project_name: os-scribe

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    binary: os-scribe

archive:
  replacements:
    linux: linux
    amd64: x86_64
  files:
    - none*

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^scratch:"
before:
  hooks:
    - go mod tidy
